### ISSUE TITLE
Windows CI failed for `legacy_cancel_read`

### ISSUE THREAD

**Issue by Xuanwo** [monoio-rs/monoio#280]
**Version**
List the versions of all `monoio` crates you are using. The easiest way to get
this information is using `cargo tree` subcommand:

main brance.

**Platform**
The output of `uname -a` and `ulimit -l`.

Not realted.

**Description**

https://github.com/bytedance/monoio/actions/runs/10211991928/job/28254404997?pr=279

```shell
---- legacy_cancel_read stdout ----
thread 'legacy_cancel_read' panicked at monoio\tests\tcp_connect.rs:125:59:
called `Result::unwrap()` on an `Err` value: Os { code: 10060, kind: TimedOut, message: "A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond." }
stack backtrace:
   0: rust_begin_unwind
             at /rustc/051478957371ee0084a7c0913941d2a8c4757bb9/library\std\src/panicking.rs:652:5
   1: core::panicking::panic_fmt
             at /rustc/051478957371ee0084a7c0913941d2a8c4757bb9/library\core\src/panicking.rs:72:14
   2: core::result::unwrap_failed
             at /rustc/051478957371ee0084a7c0913941d2a8c4757bb9/library\core\src/result.rs:1679:5
   3: core::result::Result<T,E>::unwrap
             at /rustc/051478957371ee0084a7c0913941d2a8c4757bb9\library\core\src/result.rs:1102:23
   4: tcp_connect::legacy_cancel_read::{{closure}}
             at .\tests\tcp_connect.rs:125:17
   5: monoio::runtime::Runtime<D>::block_on::{{closure}}::{{closure}}
             at .\src\runtime.rs:170:64
   6: monoio::macros::scoped_tls::ScopedKey<T>::set
             at .\src\macros\scoped_tls.rs:92:9
   7: monoio::runtime::Runtime<D>::block_on::{{closure}}
             at .\src\runtime.rs:145:13
   8: monoio::macros::scoped_tls::ScopedKey<T>::set
             at .\src\macros\scoped_tls.rs:92:9
   9: <monoio::driver::legacy::LegacyDriver as monoio::driver::Driver>::with
             at .\src\driver\legacy\mod.rs:356:9
  10: <monoio::time::driver::TimeDriver<D> as monoio::driver::Driver>::with
             at .\src\time\driver\mod.rs:315:9
  11: monoio::runtime::Runtime<D>::block_on
             at .\src\runtime.rs:144:9
  12: tcp_connect::legacy_cancel_read
             at .\tests\tcp_connect.rs:135:5
  13: tcp_connect::legacy_cancel_read::{{closure}}
             at .\tests\tcp_connect.rs:122:23
  14: core::ops::function::FnOnce::call_once
             at /rustc/051478957371ee0084a7c0913941d2a8c4757bb9\library\core\src\ops/function.rs:250:5
  15: core::ops::function::FnOnce::call_once
             at /rustc/051478957371ee0084a7c0913941d2a8c4757bb9/library\core\src\ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.


failures:
    legacy_cancel_read

test result: FAILED. 10 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 25.23s

```

**Comment by Xuanwo** [comment]
Fixed by @Lzzzzzt, thanks!
